### ISSUE TITLE
Acess to kg2c-tsv.tar.gz

### ISSUE THREAD

**Issue by Bboy010** [KoslickiLab/MetagenomicKG#1]
Hi Hope you're doing well. I'm trying to reproduce MetagenomicKG, but I have some issues can you help me please ?
Thanks

**Comment by ShaopengLiu1** [comment]
Hi, 

We can't provide the kg2c file directly as it's from the RTX-KG2 project. You can check here to download it: https://github.com/RTXteam/RTX-KG2

For using the MetagenomicKG, you may download our pre-built KG from Zenodo instead of building it from scratch.

Best,
Shaopeng

**Comment by Bboy010** [comment]
Thanks,

Best regards,

HONGO KOFFI ANDERSON
PhD Student in Metagenomic
Software Engineer & Geneticist

Le dim. 24 mars 2024 à 19:13, Shaopeng Liu ***@***.***> a
écrit :
